name : 'Terraform Pull Request'

on:
  push:
    branches:
      - master
jobs:
  plan-terraform-changes:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@v0.8.0
        with:
          tf_actions_version: 0.12.28
          tf_actions_subcommand: 'init'
          tf_actions_comment: true
          tf_actions_cli_credentials_hostname: app.terraform.io 
          tf_actions_cli_credentials_token: ${{ secrets.TFE_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Terraform apply'
        uses: hashicorp/terraform-github-actions@v0.8.0
        with:
          tf_actions_version: 0.12.28
          tf_actions_subcommand: 'apply'
          tf_actions_comment: true
          tf_actions_cli_credentials_hostname: app.terraform.io 
          tf_actions_cli_credentials_token: ${{ secrets.TFE_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}